namespace Origo.Bifrost.Hnitbjorg;

using System.Reflection;
using System.Security.AccessControl;
using System.Telemetry;

/// <summary>
/// Takes the data of the published <c>Origo Cloud Events Storage</c> app over into
/// Bifrost Hnitbjorg the first time this app is installed in a company. For every
/// (old table, new table) pair the old table is copied with <c>DataTransfer</c> when it
/// still exists in the database and the new table is empty, and every user that was
/// assigned the old permission set is granted the Bifrost one. Each field is only added to
/// the transfer when <c>RecordRef.FieldExist</c> confirms it is still present on the old
/// table: the published app's schema is not guaranteed to be byte-identical across every
/// environment, and a missing field would otherwise fail the whole install. Transient tables
/// (upload sessions and chunks) are not copied.
/// Generated by <c>tools/gen_install.py</c> and then edited by hand to add the FieldExist
/// guards and the single install entry point - regenerate with care.
/// </summary>
codeunit 10035676 "Storage Takeover ori"
{
    Access = Internal;

    /// <summary>
    /// Runs the whole take-over. Called from "Storage Install ori".OnInstallAppPerCompany before
    /// the app registers anything of its own, so the copied setup is already in place. This
    /// codeunit is deliberately not an install codeunit itself - the app has one install entry
    /// point and the order of the steps is visible there.
    /// </summary>
    internal procedure TakeOverAll()
    begin
        TakeOverData();
        TakeOverAccessControl();
    end;

    local procedure TakeOverData()
    begin
        TakeOverStorageAttachmentLink();
        TakeOverStorageSetup();
    end;

    /// <summary>Copies <c>CE Storage Attachment Link</c> (10075985) into <c>Storage Attachment Link ori</c> (10035635).</summary>
    local procedure TakeOverStorageAttachmentLink()
    var
        Target: Record "Storage Attachment Link ori";
        OldRef: RecordRef;
        DataTransfer: DataTransfer;
        FieldNo: Integer;
    begin
        if not OldTableExists(10075985) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10075985, Database::"Storage Attachment Link ori");
        OldRef.Open(10075985);
        for FieldNo := 1 to 10 do
            if OldRef.FieldExist(FieldNo) then
                DataTransfer.AddFieldValue(FieldNo, FieldNo);
        OldRef.Close();
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Storage Attachment Link ori', Target.Count());
    end;

    /// <summary>Copies <c>Cloud Events Storage Setup</c> (10075986) into <c>Storage Setup ori</c> (10035636).</summary>
    local procedure TakeOverStorageSetup()
    var
        Target: Record "Storage Setup ori";
        OldRef: RecordRef;
        DataTransfer: DataTransfer;
        FieldNo: Integer;
    begin
        if not OldTableExists(10075986) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10075986, Database::"Storage Setup ori");
        OldRef.Open(10075986);
        for FieldNo := 1 to 8 do
            if OldRef.FieldExist(FieldNo) then
                DataTransfer.AddFieldValue(FieldNo, FieldNo);
        OldRef.Close();
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        ShiftEnumOrdinals(Target, Target.FieldNo("Storage Type"), 92700, 92799, 3500);
        LogTakeOver('Storage Setup ori', Target.Count());
    end;

    /// <summary>Grants the Bifrost permission set to every user that held the old one.</summary>
    local procedure TakeOverAccessControl()
    var
        OldAccessControl: Record "Access Control";
        NewAccessControl: Record "Access Control";
        NewAppId: Guid;
        Migrated: Integer;
    begin
        NewAppId := AppId();
        OldAccessControl.SetRange("Role ID", 'CE Storage');
        OldAccessControl.SetRange("App ID", OldAppId());
        if OldAccessControl.FindSet() then
            repeat
                if not NewAccessControl.Get(
                    OldAccessControl."User Security ID", 'BIFROST Hnitbj. ori', OldAccessControl."Company Name",
                    OldAccessControl.Scope, NewAppId)
                then begin
                    NewAccessControl.Init();
                    NewAccessControl."User Security ID" := OldAccessControl."User Security ID";
                    NewAccessControl."Role ID" := 'BIFROST Hnitbj. ori';
                    NewAccessControl."Company Name" := OldAccessControl."Company Name";
                    NewAccessControl.Scope := OldAccessControl.Scope;
                    NewAccessControl."App ID" := NewAppId;
                    if NewAccessControl.Insert(true) then
                        Migrated += 1;
                end;
            until OldAccessControl.Next() = 0;
        if Migrated > 0 then
            LogTakeOver('Access Control', Migrated);
    end;

    /// <summary>Reports whether the published Cloud Events Storage table still exists in the database.</summary>
    local procedure OldTableExists(OldTableId: Integer): Boolean
    var
        TableMetadata: Record "Table Metadata";
    begin
        exit(TableMetadata.Get(OldTableId));
    end;

    /// <summary>Shifts raw enum ordinals that came from the old app's object id range.</summary>
    local procedure ShiftEnumOrdinals(TargetVariant: Variant; TargetFieldNo: Integer; FromOrdinal: Integer; ToOrdinal: Integer; Offset: Integer)
    var
        RecRef: RecordRef;
        TargetField: FieldRef;
        Ordinal: Integer;
    begin
        RecRef.GetTable(TargetVariant);
        if not RecRef.FindSet(true) then
            exit;
        repeat
            TargetField := RecRef.Field(TargetFieldNo);
            Ordinal := TargetField.Value();
            if (Ordinal >= FromOrdinal) and (Ordinal <= ToOrdinal) then begin
                TargetField.Value(Ordinal + Offset);
                RecRef.Modify(false);
            end;
        until RecRef.Next() = 0;
    end;

    local procedure LogTakeOver(TableName: Text; RowCount: Integer)
    var
        Telemetry: Codeunit Telemetry;
        Dimensions: Dictionary of [Text, Text];
    begin
        Dimensions.Add('table', TableName);
        Dimensions.Add('rows', Format(RowCount, 0, 9));
        Telemetry.LogMessage(
            'ORI-BIF-0001', TakeOverTelemetryTxt, Verbosity::Normal,
            DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, Dimensions);
    end;

    local procedure OldAppId(): Guid
    begin
        exit('7acf9361-f558-442b-a516-f5e5dd92aecb');
    end;

    local procedure AppId(): Guid
    var
        AppInfo: ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(AppInfo);
        exit(AppInfo.Id());
    end;

    var
        TakeOverTelemetryTxt: Label 'Bifrost Hnitbjorg took data over from Origo Cloud Events Storage.', Locked = true;
}
