namespace Origo.Bifrost.Attachments;

using System.Reflection;
using System.Security.AccessControl;
using System.Telemetry;

/// <summary>
/// Takes the data of the published <c>Origo Cloud Events Storage</c> app over into
/// Bifrost Attachments the first time this app is installed in a company. For every
/// (old table, new table) pair the old table is copied with <c>DataTransfer</c> when it
/// still exists in the database and the new table is empty, and every user that was
/// assigned the old permission set is granted the Bifrost one. Each field is only added to
/// the transfer when <c>RecordRef.FieldExist</c> confirms it is still present on the old
/// table: the published app's schema is not guaranteed to be byte-identical across every
/// environment, and a missing field would otherwise fail the whole install. Transient tables
/// (upload sessions and chunks) are not copied.
/// <para>
/// Install probes permissions first (<c>TryProbeTakeOverPermissions</c> / issue #8) so a
/// missing tabledata grant never raises during <c>OnInstallAppPerCompany</c>. First denial
/// skips the whole take-over with one telemetry event; never Error. Only legacy Cloud Events
/// tables 10075985 / 10075986 are sources — never Foundation <c>Setup ori</c>.
/// </para>
/// Generated by <c>tools/gen_install.py</c> and then edited by hand to add the FieldExist
/// guards and the single install entry point - regenerate with care.
/// </summary>
codeunit 10035676 "Storage Takeover ori"
{
    Access = Internal;
    Permissions = tabledata "Access Control" = RI;

    /// <summary>
    /// Runs the whole take-over. Called from "Storage Install ori".OnInstallAppPerCompany before
    /// the app registers anything of its own, so the copied setup is already in place. This
    /// codeunit is deliberately not an install codeunit itself - the app has one install entry
    /// point and the order of the steps is visible there.
    /// </summary>
    procedure TakeOverAll()
    begin
        TakeOverData();
        TakeOverAccessControl();
    end;

    /// <summary>
    /// Install entry: probes legacy tabledata permissions first, then runs <see cref="TakeOverAll"/>.
    /// On probe denial records telemetry and returns false without Error (A1: telemetry only).
    /// </summary>
    /// <returns>True when take-over ran; false when skipped after a permission probe denial.</returns>
    internal procedure TryRunTakeOverAtInstall(): Boolean
    var
        DeniedTableId: Integer;
        ProbeErrorText: Text;
    begin
        if not TryProbeTakeOverPermissions(DeniedTableId) then begin
            if DeniedTableId = Database::"Access Control" then
                ProbeErrorText := StrSubstNo('TableData %1 Write denied (install probe)', DeniedTableId)
            else
                ProbeErrorText := StrSubstNo('TableData %1 Read denied (install probe)', DeniedTableId);
            LogTakeOverSkipped(DeniedTableId, ProbeErrorText);
            exit(false);
        end;

        TakeOverAll();
        exit(true);
    end;

    /// <summary>
    /// Probes ReadPermission on each legacy source table that still exists, and WritePermission
    /// on Access Control when role pairs would move. Mirrors Foundation
    /// <c>Take-Over ori.TryProbeTakeOverPermissions</c>. Never raises.
    /// </summary>
    /// <param name="DeniedTableId">Set to the first denied table id; 0 when the probe passes.</param>
    /// <returns>True when every required grant is present (or the legacy table is absent).</returns>
    internal procedure TryProbeTakeOverPermissions(var DeniedTableId: Integer): Boolean
    var
        TableMetadata: Record "Table Metadata";
        TakeoverState: Codeunit "Storage Takeover State ori";
        RecRef: RecordRef;
        SourceTableIds: List of [Integer];
        SourceTableId: Integer;
        Index: Integer;
        ForcedDenialTableId: Integer;
    begin
        DeniedTableId := 0;
        if TakeoverState.TryGetProbeDenial(ForcedDenialTableId) then begin
            DeniedTableId := ForcedDenialTableId;
            exit(false);
        end;

        SourceTableIds.Add(10075985); // CE Storage Attachment Link
        SourceTableIds.Add(10075986); // Cloud Events Storage Setup
        for Index := 1 to SourceTableIds.Count() do begin
            SourceTableId := SourceTableIds.Get(Index);
            if TableMetadata.Get(SourceTableId) then begin
                RecRef.Open(SourceTableId);
                if not RecRef.ReadPermission() then begin
                    DeniedTableId := SourceTableId;
                    RecRef.Close();
                    exit(false);
                end;
                RecRef.Close();
            end;
        end;

        if HasLegacyAccessControlToMove() then begin
            RecRef.Open(Database::"Access Control");
            if not RecRef.WritePermission() then begin
                DeniedTableId := Database::"Access Control";
                RecRef.Close();
                exit(false);
            end;
            RecRef.Close();
        end;
        exit(true);
    end;

    local procedure TakeOverData()
    begin
        TakeOverStorageAttachmentLink();
        TakeOverStorageSetup();
    end;

    /// <summary>Copies <c>CE Storage Attachment Link</c> (10075985) into <c>Storage Attachment Link ori</c> (10035635).</summary>
    local procedure TakeOverStorageAttachmentLink()
    var
        Target: Record "Storage Attachment Link ori";
        OldRef: RecordRef;
        DataTransfer: DataTransfer;
        FieldNo: Integer;
    begin
        if not OldTableExists(10075985) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10075985, Database::"Storage Attachment Link ori");
        OldRef.Open(10075985);
        for FieldNo := 1 to 10 do
            if OldRef.FieldExist(FieldNo) then
                DataTransfer.AddFieldValue(FieldNo, FieldNo);
        OldRef.Close();
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        LogTakeOver('Storage Attachment Link ori', Target.Count());
    end;

    /// <summary>Copies <c>Cloud Events Storage Setup</c> (10075986) into <c>Storage Setup ori</c> (10035636).</summary>
    local procedure TakeOverStorageSetup()
    var
        Target: Record "Storage Setup ori";
        OldRef: RecordRef;
        DataTransfer: DataTransfer;
        FieldNo: Integer;
    begin
        if not OldTableExists(10075986) then
            exit;
        if not Target.IsEmpty() then
            exit;
        DataTransfer.SetTables(10075986, Database::"Storage Setup ori");
        OldRef.Open(10075986);
        for FieldNo := 1 to 8 do
            if OldRef.FieldExist(FieldNo) then
                DataTransfer.AddFieldValue(FieldNo, FieldNo);
        OldRef.Close();
        DataTransfer.UpdateAuditFields(false);
        DataTransfer.CopyRows();
        ShiftEnumOrdinals(Target, Target.FieldNo("Storage Type"), 92700, 92799, 3500);
        LogTakeOver('Storage Setup ori', Target.Count());
    end;

    /// <summary>
    /// Grants the Bifrost permission set to every user that held the old one.
    /// Exposed as <c>internal</c> so unit tests can exercise the Access Control path directly
    /// (same pattern as Foundation <c>MovePermissionSet</c>).
    /// </summary>
    /// <returns>The number of Access Control rows inserted.</returns>
    internal procedure TakeOverAccessControl() Migrated: Integer
    var
        OldAccessControl: Record "Access Control";
        NewAccessControl: Record "Access Control";
        NewAppId: Guid;
    begin
        NewAppId := AppId();
        OldAccessControl.ReadIsolation := IsolationLevel::ReadCommitted;
        OldAccessControl.SetLoadFields("User Security ID", "Company Name", Scope);
        OldAccessControl.SetRange("Role ID", 'CE Storage');
        OldAccessControl.SetRange("App ID", OldAppId());
        if not OldAccessControl.FindSet() then
            exit(0);
        repeat
            if not NewAccessControl.Get(
                OldAccessControl."User Security ID", 'BIFROST Attach ori', OldAccessControl."Company Name",
                OldAccessControl.Scope, NewAppId)
            then begin
                NewAccessControl.Init();
                NewAccessControl."User Security ID" := OldAccessControl."User Security ID";
                NewAccessControl."Role ID" := 'BIFROST Attach ori';
                NewAccessControl."Company Name" := OldAccessControl."Company Name";
                NewAccessControl.Scope := OldAccessControl.Scope;
                NewAccessControl."App ID" := NewAppId;
                if NewAccessControl.Insert(true) then
                    Migrated += 1;
            end;
        until OldAccessControl.Next() = 0;
        if Migrated > 0 then
            LogTakeOver('Access Control', Migrated);
    end;

    /// <summary>
    /// Whether any Access Control row of Origo Cloud Events Storage matches Role ID
    /// <c>CE Storage</c>. When none exist, the Access Control write probe is skipped.
    /// </summary>
    local procedure HasLegacyAccessControlToMove(): Boolean
    var
        OldAccessControl: Record "Access Control";
    begin
        OldAccessControl.ReadIsolation := IsolationLevel::ReadCommitted;
        OldAccessControl.SetRange("Role ID", 'CE Storage');
        OldAccessControl.SetRange("App ID", OldAppId());
        exit(not OldAccessControl.IsEmpty());
    end;

    /// <summary>Emits one telemetry event for a skipped install take-over and records it for tests.</summary>
    local procedure LogTakeOverSkipped(DeniedTableId: Integer; ErrorText: Text)
    var
        Telemetry: Codeunit Telemetry;
        TakeoverState: Codeunit "Storage Takeover State ori";
        Dimensions: Dictionary of [Text, Text];
    begin
        Dimensions.Add('company', CompanyName());
        Dimensions.Add('tableId', Format(DeniedTableId, 0, 9));
        Dimensions.Add('error', CopyStr(ErrorText, 1, 250));
        TakeoverState.SetLastSkip(DeniedTableId, ErrorText);
        Telemetry.LogMessage(
            'ORI-BIF-0002', TakeOverSkippedTelemetryTxt, Verbosity::Normal,
            DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, Dimensions);
    end;

    /// <summary>Reports whether the published Cloud Events Storage table still exists in the database.</summary>
    local procedure OldTableExists(OldTableId: Integer): Boolean
    var
        TableMetadata: Record "Table Metadata";
    begin
        exit(TableMetadata.Get(OldTableId));
    end;

    /// <summary>Shifts raw enum ordinals that came from the old app's object id range.</summary>
    local procedure ShiftEnumOrdinals(TargetVariant: Variant; TargetFieldNo: Integer; FromOrdinal: Integer; ToOrdinal: Integer; Offset: Integer)
    var
        RecRef: RecordRef;
        TargetField: FieldRef;
        Ordinal: Integer;
    begin
        RecRef.GetTable(TargetVariant);
        if not RecRef.FindSet(true) then
            exit;
        repeat
            TargetField := RecRef.Field(TargetFieldNo);
            Ordinal := TargetField.Value();
            if (Ordinal >= FromOrdinal) and (Ordinal <= ToOrdinal) then begin
                TargetField.Value(Ordinal + Offset);
                RecRef.Modify(false);
            end;
        until RecRef.Next() = 0;
    end;

    local procedure LogTakeOver(TableName: Text; RowCount: Integer)
    var
        Telemetry: Codeunit Telemetry;
        Dimensions: Dictionary of [Text, Text];
    begin
        Dimensions.Add('table', TableName);
        Dimensions.Add('rows', Format(RowCount, 0, 9));
        Telemetry.LogMessage(
            'ORI-BIF-0001', TakeOverTelemetryTxt, Verbosity::Normal,
            DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, Dimensions);
    end;

    local procedure OldAppId(): Guid
    begin
        exit('7acf9361-f558-442b-a516-f5e5dd92aecb');
    end;

    local procedure AppId(): Guid
    var
        AppInfo: ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(AppInfo);
        exit(AppInfo.Id());
    end;

    var
        TakeOverTelemetryTxt: Label 'Bifrost Attachments took data over from Origo Cloud Events Storage.', Locked = true;
        TakeOverSkippedTelemetryTxt: Label 'Bifrost Attachments take-over skipped at install (permission probe).', Locked = true;
}
