"""Generates the Bifrost Hnitbjorg data take-over install codeunit.

The new app is published side by side with the published *Origo Cloud Events Storage*
app, so on first install it copies that app's persistent tables into its own and
re-grants its permission set to every user who had the old one.

The old -> new table id map, the field lists and the permission-set map are read from
the two repositories - nothing is typed by hand. Re-run after any table change:

    python tools/gen_install.py

Writes app/src/Install/StorageTakeover.Codeunit.al
"""
import os
import re
import sys
import glob

LEGACY = r"D:/Git/Origo/OrigoSoftwareSolutions/bc-cloudevents-storage/Cloud Events Storage/src"
NEW = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "app", "src")
OUT = os.path.join(NEW, "Install", "StorageTakeover.Codeunit.al")
OFFSET = -40350                      # new object id - old object id
TEST_OFFSET = 3500                   # new test object id - old test object id
CODEUNIT_ID = 10035676
CODEUNIT_NAME = "Storage Takeover ori"

# Transient tables are never copied (upload buffers are discarded between sessions).
SKIP_TABLES = {"CE Storage Upload Chunk", "CE Storage Upload Session"}

# Enum-valued fields whose ordinals come from the old app's own object id ranges and
# therefore have to be shifted after the raw copy.
ENUM_REMAP = [("Storage Setup ori", "Storage Type", 92700, 92799, TEST_OFFSET)]

PERMISSION_SETS = {"CE Storage": "BIFROST Hnitbj. ori"}
OLD_APP_ID = "7acf9361-f558-442b-a516-f5e5dd92aecb"

TABLE_RE = re.compile(r'^\s*table\s+(\d+)\s+"([^"]+)"', re.M)
FIELD_RE = re.compile(r'^\s*field\((\d+);\s*([^;]+);\s*(.+?)\)\s*$', re.M)


def tables(root):
    found = {}
    for path in glob.glob(os.path.join(root, "**", "*.Table.al"), recursive=True):
        txt = open(path, "rb").read().decode("utf-8-sig")
        m = TABLE_RE.search(txt)
        if not m:
            continue
        fields = [(int(f[0]), f[1].strip().strip(chr(34)), f[2].strip()) for f in FIELD_RE.findall(txt)]
        found[int(m.group(1))] = (m.group(2), fields, path)
    return found


old, new = tables(LEGACY), tables(NEW)
pairs = []
for old_id in sorted(old):
    old_name, old_fields, _ = old[old_id]
    if old_name in SKIP_TABLES:
        continue
    new_id = old_id + OFFSET
    if new_id not in new:
        sys.exit("no new table for %d %s" % (old_id, old_name))
    new_name, new_fields, _ = new[new_id]
    old_nos = set(f[0] for f in old_fields)
    common = [f for f in new_fields if f[0] in old_nos and f[2].lower() != "blob"]
    if not common:
        sys.exit("no common fields for %s" % new_name)
    pairs.append((old_id, old_name, new_id, new_name, common))

L = []
w = L.append
q = '"'
w("namespace Origo.Bifrost.Hnitbjorg;")
w("")
w("using System.Reflection;")
w("using System.Security.AccessControl;")
w("using System.Telemetry;")
w("")
w("/// <summary>")
w("/// Takes the data of the published <c>Origo Cloud Events Storage</c> app over into")
w("/// Bifrost Hnitbjorg the first time this app is installed in a company. For every")
w("/// (old table, new table) pair the old table is copied with <c>DataTransfer</c> when it")
w("/// still exists in the database and the new table is empty, and every user that was")
w("/// assigned the old permission set is granted the Bifrost one. Transient tables (upload")
w("/// sessions and chunks) are not copied. Generated by <c>tools/gen_install.py</c> -")
w("/// do not edit by hand.")
w("/// </summary>")
w("codeunit %d %s%s%s" % (CODEUNIT_ID, q, CODEUNIT_NAME, q))
w("{")
w("    Subtype = Install;")
w("    Access = Internal;")
w("")
w("    trigger OnInstallAppPerCompany()")
w("    begin")
w("        TakeOverData();")
w("        TakeOverAccessControl();")
w("    end;")
w("")
w("    local procedure TakeOverData()")
w("    begin")
for pair in pairs:
    w("        TakeOver%s();" % re.sub(r"[^A-Za-z0-9]", "", pair[3].replace(" ori", "")))
w("    end;")
w("")

for old_id, old_name, new_id, new_name, fields in pairs:
    proc = re.sub(r"[^A-Za-z0-9]", "", new_name.replace(" ori", ""))
    w("    /// <summary>Copies <c>%s</c> (%d) into <c>%s</c> (%d).</summary>" % (old_name, old_id, new_name, new_id))
    w("    local procedure TakeOver%s()" % proc)
    w("    var")
    w("        Target: Record %s%s%s;" % (q, new_name, q))
    w("        DataTransfer: DataTransfer;")
    w("    begin")
    w("        if not OldTableExists(%d) then" % old_id)
    w("            exit;")
    w("        if not Target.IsEmpty() then")
    w("            exit;")
    w("        DataTransfer.SetTables(%d, Database::%s%s%s);" % (old_id, q, new_name, q))
    for no, name, typ in fields:
        w("        DataTransfer.AddFieldValue(%d, %d);" % (no, no))
    w("        DataTransfer.UpdateAuditFields(false);")
    w("        DataTransfer.CopyRows();")
    for remap in [r for r in ENUM_REMAP if r[0] == new_name]:
        w("        ShiftEnumOrdinals(Target, Target.FieldNo(%s%s%s), %d, %d, %d);"
          % (q, remap[1], q, remap[2], remap[3], remap[4]))
    w("        LogTakeOver('%s', Target.Count());" % new_name)
    w("    end;")
    w("")

w("    /// <summary>Grants the Bifrost permission set to every user that held the old one.</summary>")
w("    local procedure TakeOverAccessControl()")
w("    var")
w("        OldAccessControl: Record %sAccess Control%s;" % (q, q))
w("        NewAccessControl: Record %sAccess Control%s;" % (q, q))
w("        NewAppId: Guid;")
w("        Migrated: Integer;")
w("    begin")
w("        NewAppId := AppId();")
for old_set in sorted(PERMISSION_SETS):
    new_set = PERMISSION_SETS[old_set]
    w("        OldAccessControl.SetRange(%sRole ID%s, '%s');" % (q, q, old_set))
    w("        OldAccessControl.SetRange(%sApp ID%s, OldAppId());" % (q, q))
    w("        if OldAccessControl.FindSet() then")
    w("            repeat")
    w("                if not NewAccessControl.Get(")
    w("                    OldAccessControl.%sUser Security ID%s, '%s', OldAccessControl.%sCompany Name%s,"
      % (q, q, new_set, q, q))
    w("                    OldAccessControl.Scope, NewAppId)")
    w("                then begin")
    w("                    NewAccessControl.Init();")
    w("                    NewAccessControl.%sUser Security ID%s := OldAccessControl.%sUser Security ID%s;" % (q, q, q, q))
    w("                    NewAccessControl.%sRole ID%s := '%s';" % (q, q, new_set))
    w("                    NewAccessControl.%sCompany Name%s := OldAccessControl.%sCompany Name%s;" % (q, q, q, q))
    w("                    NewAccessControl.Scope := OldAccessControl.Scope;")
    w("                    NewAccessControl.%sApp ID%s := NewAppId;" % (q, q))
    w("                    if NewAccessControl.Insert(true) then")
    w("                        Migrated += 1;")
    w("                end;")
    w("            until OldAccessControl.Next() = 0;")
w("        if Migrated > 0 then")
w("            LogTakeOver('Access Control', Migrated);")
w("    end;")
w("")
w("    /// <summary>Reports whether the published Cloud Events Storage table still exists in the database.</summary>")
w("    local procedure OldTableExists(OldTableId: Integer): Boolean")
w("    var")
w("        TableMetadata: Record %sTable Metadata%s;" % (q, q))
w("    begin")
w("        exit(TableMetadata.Get(OldTableId));")
w("    end;")
w("")
w("    /// <summary>Shifts raw enum ordinals that came from the old app's object id range.</summary>")
w("    local procedure ShiftEnumOrdinals(TargetVariant: Variant; TargetFieldNo: Integer; FromOrdinal: Integer; ToOrdinal: Integer; Offset: Integer)")
w("    var")
w("        RecRef: RecordRef;")
w("        TargetField: FieldRef;")
w("        Ordinal: Integer;")
w("    begin")
w("        RecRef.GetTable(TargetVariant);")
w("        if not RecRef.FindSet(true) then")
w("            exit;")
w("        repeat")
w("            TargetField := RecRef.Field(TargetFieldNo);")
w("            Ordinal := TargetField.Value();")
w("            if (Ordinal >= FromOrdinal) and (Ordinal <= ToOrdinal) then begin")
w("                TargetField.Value(Ordinal + Offset);")
w("                RecRef.Modify(false);")
w("            end;")
w("        until RecRef.Next() = 0;")
w("    end;")
w("")
w("    local procedure LogTakeOver(TableName: Text; RowCount: Integer)")
w("    var")
w("        Telemetry: Codeunit Telemetry;")
w("        Dimensions: Dictionary of [Text, Text];")
w("    begin")
w("        Dimensions.Add('table', TableName);")
w("        Dimensions.Add('rows', Format(RowCount, 0, 9));")
w("        Telemetry.LogMessage(")
w("            'ORI-BIF-0001', TakeOverTelemetryTxt, Verbosity::Normal,")
w("            DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, Dimensions);")
w("    end;")
w("")
w("    local procedure OldAppId(): Guid")
w("    begin")
w("        exit('%s');" % OLD_APP_ID)
w("    end;")
w("")
w("    local procedure AppId(): Guid")
w("    var")
w("        AppInfo: ModuleInfo;")
w("    begin")
w("        NavApp.GetCurrentModuleInfo(AppInfo);")
w("        exit(AppInfo.Id());")
w("    end;")
w("")
w("    var")
w("        TakeOverTelemetryTxt: Label 'Bifrost Hnitbjorg took data over from Origo Cloud Events Storage.', Locked = true;")
w("}")
w("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "wb").write(b"\xef\xbb\xbf" + "\n".join(L).encode("utf-8"))
print("wrote", OUT)
for old_id, old_name, new_id, new_name, fields in pairs:
    print("  %-30s %d -> %-30s %d  (%d fields)" % (old_name, old_id, new_name, new_id, len(fields)))
print("  permission sets:", PERMISSION_SETS)
